# Generated by Django 6.0.5 on 2026-05-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delevery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleviryinformation',
            name='gender',
        ),
    ]
