# Generated by Django 6.0.5 on 2026-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delevery', '0002_remove_deleviryinformation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleviryinformation',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
